### ISSUE TITLE
Possible README Updates

### ISSUE THREAD

**Issue by mkrump** [transcom/mymove#1581]
Ran into a few minor issues when setting up app for first time. Wasn't sure if these were README updates or something on my end.

* The swagger docs endpoint on `localhost` wasn't working for me (i.e. `Bad Request`), but on `milmovelocal` it did. So in README should it be `http://milmovelocal:3000/api/v1/docs` instead of `http://localhost:3000/api/v1/docs`?
https://github.com/transcom/mymove/blob/4e13b84ea23e8f462e0d3c4ff9ba559dc6b6e4f8/README.md#L256

* The `Test Data Generator` section has some info about a rounds flag for `generate-test-data`. I didn't see a rounds flag, so was wondering if that part could be dropped?
https://github.com/transcom/mymove/blob/4e13b84ea23e8f462e0d3c4ff9ba559dc6b6e4f8/README.md#L234

**Comment by chrisgilmerproj** [comment]
Let's open up a pivotal story to track this one (or feel free to make a PR!).

**Comment by chrisgilmerproj** [comment]
See https://www.pivotaltracker.com/story/show/163276823
