### ISSUE TITLE
MTO Entities Database Diagram

### ISSUE THREAD

**Issue by ralren** [transcom/mymove#2879]
This is version two of the DB diagram for MTO and other related entities. This was created using the tool dbdiagram.io. You can find the specific link here: https://dbdiagram.io/d/5db7168afa792a62f50d9625

To identify the kind of relationships the tables have with each other, note there is either a `1` or a `*` at each end of the line connecting two tables together. `1` stands for one and `*` stands for many. 

This was worked under the assumption that `customers` would be a renamed `service_members` table. Also I didn't put all the fields on already established tables within the diagram. I only placed what seemed relevant to MTO entities. I believe the only information I'm truly missing is where electronic copy of orders, travel authorization issuing HQ, and data the PRIME will add to the MTO. 

There is no longer an `entitlements` table. This has been absorbed into the `orders` table as it was noted that this table already had properties indicating information pertaining to entitlements such as `has_dependents` and `spouse_has_pro_gear`. It made sense to me to expand the table rather than introducing a new one.

Another change is that there is no longer an `origin_duty_station_id` and `customer_id` on the `move_task_orders` table. This information was already provided by the parent models to MTOs and it was pointed out to me that this meant we didn't necessarily require that data on MTO.

<img width="1562" alt="Screen Shot 2019-10-30 at 10 45 27 AM" src="https://user-images.githubusercontent.com/6464062/67868471-6ab0f880-fb02-11e9-9f5e-3313982cd43e.png">

**Comment by sarboc** [comment]
I'm not sure what level of review you're looking for here, but the service items table is likely to be set up differently than what is in this diagram. TTV will be tackling that soon. Additionally, your PR description says, "customers will be renamed to service_members". Is that correct, or is it the other way around? I thought we wanted to move forward with "customers" as our new terminology.

**Comment by ralren** [comment]
I wrote _would_ be renamed from `customers` to `service_members`. That's alright if the `service_items` is likely to be set up differently. I expect this diagram to be constantly changing until we get a MVP.

**Comment by ralren** [comment]
Closing this as a new story will capture changes needed to be made in light of the news from the latest demo.
