### ISSUE TITLE
Add files for proper tracking of contributors and contribution policy

### ISSUE THREAD

**Issue by jordangov** [transcom/mymove#67]
Hey folks! In order to comply with DoD source code policy and the guidance provided by the Code.mil efforts on OSS in DoD we need to add two additional files to this repo. One is [contributing guidelines](https://github.com/deptofdefense/move.mil/blob/master/CONTRIBUTING.md), the other is the [list of contributors](https://github.com/deptofdefense/move.mil/blob/master/CONTRIBUTORS.md). You can see examples of them in the move.mil repo (linked above). On the contributing guidelines, we really need the legalese, the other stuff about how to run the app, etc can come later if you want to just stub that out. For the contributor list, you'll notice in move.mil that DDS uses a catchall email address and blanketly states contributions by DDS are under the US federal government copyright. Other organizations may consider doing so, but otherwise the DCO process that we use (see the move.mil contributing legalese) requires a name and email address along with copyright year.

- [x] contributing guidelines
- [x] contributor list

Let me know if you have any questions! (I'm the OSS / Code.mil lead)

**Comment by jillesmith1** [comment]
@jordangov, I will run this through USTC Legal for review.

**Comment by jillesmith1** [comment]
@jordangov, please add USTC reviewed label if you can.

**Comment by jgarber623-gov** [comment]
Adding some possibly helpful links to related work from [the move.mil repo](https://github.com/deptofdefense/move.mil):

- https://github.com/deptofdefense/move.mil/blob/master/CONTRIBUTING.md
- https://github.com/deptofdefense/move.mil/blob/master/CONTRIBUTORS.md

**Comment by jillesmith1** [comment]
@jordangov, our Staff Judge Advocate approved the language as written. Ready for both files to go live in Move.mil.

**Comment by jordangov** [comment]
👍 I'll submit a PR with these files soon.

**Comment by jordangov** [comment]
Actually, seeing as I'm not really on this project (just the OSS part) and not in this GH org, maybe @jgarber623-gov can add those files in? The contributing docs will need to be maintained by the contractor I imagine (at least to start).

**Comment by jgarber623-gov** [comment]
@jordangov Probably best for Truss folks to add the docs. Y'all feel free to use the move.mil files as a reference and adjust wording accordingly!

**Comment by willowbl00** [comment]
started https://github.com/transcom/mymove/pull/268 and https://github.com/transcom/mymove/pull/269

**Comment by willowbl00** [comment]
@jordangov @jgarber623-gov do I also add in the DDS engs and Sliced Bread folk? What about Elliott, Kayless, and myself? Is it only for the code?

**Comment by jordangov** [comment]
DDS folks are covered by the "federal government" bit. Anyone else working on this that is not part of Truss should add their names, yes. A company-wide one like you have for Truss is fine, but if they are independent contractors (or the public) then they should add their names individually. This is covered in the contributing doc you have in #268.

**Comment by willowbl00** [comment]
@jgarber623-gov @jordangov I believe I have resolved this issue!
